1.21
Light-Beacon/PCL2-NewsHomepage pull request #178
Opened 2024-06-15 05:03 UTC by WYC-E

2024-06-15 06:17 UTC, WorldHim requested changes

2024-06-15 06:17 UTC, WorldHim commented on Libraries/Versions/Release/1.21.md
> + ### 加入了8个新进度。
这里也要用 h3 和 h4
另外 Ln90 不用前面加空格

2024-06-15 06:17 UTC, WorldHim commented on Libraries/Versions/Release/1.21.md
> +### 试炼密室
为啥改掉
官网就是用的 h3 和 h4
![image](https://github.com/Light-Beacon/PCL2-NewsHomepage/assets/68632311/27a6a953-2cfc-4eff-98cb-eb9b78080368)

2024-06-15 06:21 UTC, youzi-2333 commented on Libraries/Versions/Release/1.21.md
> + ### 加入了8个新进度。
数字旁边最好加两个空格，看着舒服（）

```suggestion
## 进度
### 加入了 8 个新进度。
```

2024-06-15 06:23 UTC, youzi-2333 commented on Libraries/Versions/Release/1.21.md
> + * 修复了194个漏洞
```suggestion
 * 修复了 194 个漏洞
```

2024-06-16 10:51 UTC, youzi-2333 commented on Libraries/Versions/Release/1.21.md
> + ### 加入了8个新进度。
@WYC-E 这里 Ln90 和 Ln108 前面不用加空格……麻烦改一下

2024-06-17 11:08 UTC, Light-Beacon commented
请在你的仓库merge一遍

2024-06-21 02:08 UTC, youzi-2333 commented on Libraries/Versions/Release/1.21.md
> +     * 使用风弹将自己向上弹射8格
```suggestion
     * 使用风弹将自己向上弹射 8 格
```

2024-06-21 02:08 UTC, youzi-2333 commented on Libraries/Versions/Release/1.21.md
> +     * 使用重锤一击造成50颗心的伤害
```suggestion
     * 使用重锤一击造成 50 颗心的伤害
```

2024-07-11 00:56 UTC, closed without merging