翻译：旋风人
Light-Beacon/PCL2-NewsHomepage pull request #181
Opened 2024-06-16 11:16 UTC by youzi-2333

2024-06-16 12:11 UTC, WorldHim commented
你的空格也少了😂要用四个空格

2024-06-17 11:09 UTC, Light-Beacon requested changes

2024-06-17 11:09 UTC, Light-Beacon commented on Libraries/Versions/Release/1.21.md
> +
请删除这一空行 这会导致bug

2024-06-20 02:31 UTC, youzi-2333 commented on Libraries/Versions/Release/1.21.md
> +
√ 3377f16

2024-06-20 02:34 UTC, youzi-2333 commented
。关了吧，已经有人翻过旋风人了

2024-06-20 02:34 UTC, closed without merging