加了两篇 生物 翻译······
Light-Beacon/PCL2-NewsHomepage pull request #182
Opened 2024-06-16 15:13 UTC by RimacC2-EV

我是新手翻译，翻译可能会有的对不上······欢迎批评指正！

2024-06-17 02:26 UTC, RimacC2-EV commented
有大佬来浅看一下吗······
<del> 趁没人在发个癫   :）</del>

2024-06-17 03:01 UTC, RimacC2-EV reviewed
又来了一篇 武器（Weapon）······

2024-06-17 10:35 UTC, WorldHim requested changes
需要 4 个空格缩进
另外，建议删掉无用的空行

2024-06-17 11:05 UTC, RimacC2-EV reviewed
改进基本上完成了······您能审阅一下吗

2024-06-17 11:11 UTC, Light-Beacon requested changes
需要删除无用的空行，这会导致构建器生成问题

2024-06-17 11:13 UTC, RimacC2-EV reviewed
是这样吗？

2024-06-17 11:15 UTC, Light-Beacon commented
您可以在文件最开始的`translators`后加入自己的名字以记录贡献

2024-06-17 11:15 UTC, Light-Beacon approved these changes

2024-06-17 11:22 UTC, RimacC2-EV commented
额，我要不在第 3 次 翻译的时候再写罢《

<del>哦对，忘了说了，我是史学家，这些翻译史记吧</del>

2024-06-17 11:25 UTC, Light-Beacon commented
其实现在可以合并，若你想继续贡献可以提交新的pr

2024-06-19 03:32 UTC, RimacC2-EV commented
这个 PR 能合并吗？

<del>不会出Bug了罢</del>

2024-06-20 01:10 UTC, merged